/*
 * TuringTypes.h
 *
 *  Created on: 10.12.2014
 *      Author: maxi
 */

#ifndef TURINGTYPES_H_
#define TURINGTYPES_H_

typedef long long TURING_DATA, TURING_POINTER, TURING_VERTICLE;

typedef unsigned char TURING_BAND_DATA;

enum{
	TURING_PLACE_HOLDER = (TURING_BAND_DATA) '#',
};

typedef unsigned char TURING_MOVE_TYPE;

enum{
	MOVE_RIGHT = 'r',
	MOVE_LEFT = 'l',
	MOVE_STOP = 'S',
};

enum TURING_STATE{
	TURING_STATE_NORMAL = 0,
	TURING_STATE_ACCEPTED = 1,
	TURING_STATE_REJECTED = -1,
	TURING_STATE_OLD,
};

#define TURING_INIT_STATE	(TURING_STATE) TURING_STATE_NORMAL
#define TURING_INIT_POINTER	(TURING_POINTER) 0
#define TURING_INIT_VERTICLE (TURING_VERTICLE) 0

#endif /* TURINGTYPES_H_ */
